# Site settings
title: League of Urban Canners
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  LUrC is an alternative economic model for food production where members of the
  community work together to produce food for themselves.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leagueofurbancanners.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  lurc

# Build settings
markdown: kramdown

exclude: ['vendor']
